apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/namespace.yaml
  - k8s/deployment.yaml
  - k8s/service.yaml
configMapGenerator:
  - name: site
    namespace: incident-story-generator
    files:
      - index.html=site/index.html
  - name: nginx-config
    namespace: incident-story-generator
    files:
      - default.conf=k8s/default.conf
